.PHONY: clean debug release

debug:
	@echo "----------Building project:[ SpirVTools - Debug ]----------"
	@cd "SpirVTools" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ Renderer - Debug ]----------"
	@cd "Renderer" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ OS - Debug ]----------"
	@cd "OSBase" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ 01_Transformation - Debug ]----------"
	@cd "01_Transformation" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ 02_Compute - Debug ]----------"
	@cd "02_Compute" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ 03_MultiThread - Debug ]----------"
	@cd "03_MultiThread" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ 04_ExecuteIndirect - Debug ]----------"
	@cd "04_ExecuteIndirect" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ 05_FontRendering - Debug ]----------"
	@cd "05_FontRendering" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ 06_BRDF - Debug ]----------"
	@cd "06_BRDF" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ 07_Tessellation - Debug ]----------"
	@cd "07_Tessellation" && "$(MAKE)" -f  "Debug.mk"
	@echo "----------Building project:[ 08_Procedural - Debug ]----------"
	@cd "08_Procedural" && "$(MAKE)" -f  "Debug.mk"

release:
	@echo "----------Building project:[ SpirVTools - Release ]----------"
	@cd "SpirVTools" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ Renderer - Release ]----------"
	@cd "Renderer" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ OS - Release ]----------"
	@cd "OSBase" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ 01_Transformation - Release ]----------"
	@cd "01_Transformation" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ 02_Compute - Release ]----------"
	@cd "02_Compute" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ 03_MultiThread - Release ]----------"
	@cd "03_MultiThread" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ 04_ExecuteIndirect - Release ]----------"
	@cd "04_ExecuteIndirect" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ 05_FontRendering - Release ]----------"
	@cd "05_FontRendering" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ 06_BRDF - Release ]----------"
	@cd "06_BRDF" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ 07_Tessellation - Release ]----------"
	@cd "07_Tessellation" && "$(MAKE)" -f  "Release.mk"
	@echo "----------Building project:[ 08_Procedural - Release ]----------"
	@cd "08_Procedural" && "$(MAKE)" -f  "Release.mk"


clean:
	@echo "----------Cleaning project:[ SpirVTools - Clean ]----------"
	@cd "SpirVTools" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ Renderer - Clean ]----------"
	@cd "Renderer" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ OS - Clean ]----------"
	@cd "OSBase" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ 01_Transformation - Clean ]----------"
	@cd "01_Transformation" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ 02_Compute - Clean ]----------"
	@cd "02_Compute" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ 03_MultiThread - Clean ]----------"
	@cd "03_MultiThread" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ 04_ExecuteIndirect - Clean ]----------"
	@cd "04_ExecuteIndirect" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ 05_FontRendering - Clean ]----------"
	@cd "05_FontRendering" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ 06_BRDF - Clean ]----------"
	@cd "06_BRDF" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ 07_Tessellation - Clean ]----------"
	@cd "07_Tessellation" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
	@echo "----------Cleaning project:[ 08_Procedural - Clean ]----------"
	@cd "08_Procedural" && "$(MAKE)" -f  "Debug.mk"  clean && "$(MAKE)" -f  "Release.mk"  clean
